on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 16.18.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.0

    - name: npm install, make test-coverage
      run: |
        npm install
        npm test -- --coverage && cat ./coverage/lcov.info | coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@v2